spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/SpringMyOrder}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:0d000721}
    driver-class-name: org.postgresql.Driver
  application:
    name: SpringMyOrder

server:
  error:
    include-message: always
