ALTER TABLE "user" ALTER COLUMN "name" TYPE VARCHAR(50);
ALTER TABLE "user" ALTER COLUMN qq TYPE VARCHAR(40);

ALTER TABLE "group" ALTER COLUMN "name" TYPE VARCHAR(50);
ALTER TABLE "group" ALTER COLUMN qq TYPE VARCHAR(40);

ALTER TABLE address ALTER COLUMN name TYPE VARCHAR(40);
ALTER TABLE address ALTER COLUMN phone TYPE VARCHAR(20);
ALTER TABLE address ALTER COLUMN address TYPE VARCHAR(200);

ALTER TABLE list ADD UNIQUE (user_id, item_id);

ALTER TABLE delivery ADD COLUMN creator_id BIGINT NOT NULL;
